# version: '3.8'

# services:
#   mysql:
#     image: mysql:8.0
#     container_name: mysql-employeeservice
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root      # root wachtwoord, kan je aanpassen
#       MYSQL_DATABASE: employeeservice_db          # moet matchen met jouw Spring app
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql

# volumes:
#   mysql_data:


version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-employeeservice
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employeeservice_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-employeeservice
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8083:80"

volumes:
  mysql_data:
